# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
timezone: America/New_York
title: VizFin - Visualizing Finance
email: beconae@gmail.com
description: Educational Finance Visualizations using Javascript
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rickpaul.github.io/viz-fin" # the base hostname & protocol for your site
github_username:  rickpaul

# Build settings
markdown: kramdown